# Generated by Django 3.2.8 on 2021-11-10 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211108_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 14, 43, 2, 842866, tzinfo=utc)),
        ),
    ]
